### ISSUE TITLE
Is not working with EXML 7.0

### ISSUE THREAD

**Issue by andrewhj** [andrewhj/dbunit-extension#405]
1\. If I set classpath like this
dbunit.jar;exml.jar\(dbunit\);exml.jar\(EXML 7.0\) than
Glue \(ver. 4.1.2\) is not working.

Glue Error message:
java.lang.RuntimeException:
java.lang.NoSuchMethodError:
electric.xml.Document.&amp;lt;init&amp;gt;\(\[BI\)V
	at
electric.util.product.Product.startupAsServer\(Unknown
Source\)
	at
electric.util.product.Product.startupAsServer\(Unknown
Source\)
	at electric.server.http.HTTP.startup\(Unknown Source\)
	at electric.server.http.HTTP.startup\(Unknown Source\)
	at com.ipad.server.Launcher.main\(Launcher.java:17\)
Exception in thread &amp;quot;main&amp;quot;

2\. On other hand, if I set classpath
dbunit.jar;exml.jar\(EXML 7.0\);exml.jar\(dbunit\) than
DBUnit is not working.

DBUnit Error Message:
junit.framework.TestSuite@e79839java.lang.VerifyError:
\(class: org/dbunit/dataset/xml/XmlDataSet, method:
getTables signature:
\(Lelectric/xml/Document;\)\[Lorg/dbunit/dataset/ITable;\)
Incompatible object argument for function call
